//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_business.Connect
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bookings
    {
        public Bookings()
        {
            this.Payments = new HashSet<Payments>();
            this.BookingServices = new HashSet<BookingServices>();
        }
    
        public int BookingId { get; set; }
        public int UserId { get; set; }
        public int RoomId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Status { get; set; }
    
        public virtual Rooms Rooms { get; set; }
        public virtual Users Users { get; set; }
        public virtual ICollection<Payments> Payments { get; set; }
        public virtual ICollection<BookingServices> BookingServices { get; set; }
    }
}
